<?php
namespace Admin\Controller;

use Admin\Controller\AppController;
use Cake\ORM\TableRegistry;

class WelcomeController extends AppController
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->AuthRule->allow(['index', 'main']);
    }

    /**
     * 框架入口
     */
    public function index()
    {
        $userData = $this->Auth->user();
        $menuData = TableRegistry::getTableLocator()->get('Admin.Menus')->getMenu($userData['role_id']);
        $systemData = TableRegistry::getTableLocator()->get('Admin.Options')->getArrayData(array('Options.type' => 'system'));

        $this->set(compact('userData', 'menuData', 'systemData'));
    }

    /**
     * 我的主页
     */
    public function main()
    {

    }
}
